services:
  golang-backend:
    build:
      context: backend/go-impl/
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
      - "9876:9876"
    volumes:
      - ./volume/data:/app/audio
    env_file:
      - backend/go-impl/.env
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "3000:3000"
    volumes:
      # 可选：如果你想在开发时实时更新 public 目录下的内容而无需重建镜像
      # 请确保 ./public 目录存在
      - ./volume/frontend/public:/usr/share/nginx/html/public:ro
      # 可选：如果你想在开发时实时更新 nginx 配置而无需重建镜像
      - ./volume/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - golang-backend
    env_file:
      - backend/go-impl/.env
    networks:
      - app-network

  predictor-server:
    build:
      context: .
      dockerfile: Dockerfile-predictor
    ports:
      - "8000:8000"
    networks:
      - app-network

# 如果使用vits语音docker，请将其docker加入lingchat container network, 否则后端无法与其通信生成语音
# docker network connect lingchat_app-network vits-simple-api-vits

networks:
  app-network:
    driver: bridge