[tool.poetry]
name = "py-ling-chat"
version = "0.1.0"
description = ""
authors = ["0x00-pl <0x00.pl@gmail.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "torchcpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

#[[tool.poetry.source]]
#name = "artrajz"
#url = "https://pypi.artrajz.cn/simple/"
#priority = "explicit"


[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.11,<3.14"
dotenv = "^0.9.9"
fastapi = "^0.115.12"
uvicorn = "^0.34.3"
requests = "^2.32.4"
aiohttp = "^3.12.11"
torch = {version = "^2.7.1+cpu", source = "torchcpu"}
transformers = "^4.52.4"
pywebview = "^5.4"
openai = "^1.85.0"
platformdirs = "^4.3.8"
python-multipart = "^0.0.20"
websockets = "^15.0.1"

#[tool.poetry.group.vits.dependencies]
#logzero = "^1.7.0"
#ngrok = "^1.4"
#flask = "^3.1.1"
#flask-apscheduler = "^1.13.1"
#flask-login = "^0.6.3"
#flask-wtf = "^1.2.2"
#flask-cors = "^6.0.1"
#pypinyin-dict = "^0.9.0"
#jieba = "^0.42.1"
#py-cpuinfo = "^9.0.0"
#psutil = "^7.0.0"
#llvmlite = "^0.44.0"
#librosa = "^0.11.0"
#vector-quantize-pytorch = "^1.22.16"
#cn2an = "^0.5.23"
#num2words = "^0.5.14"
#pyopenjtalk = "^0.4.1"
#jaconv = "^0.4.0"
#g2p-en = "^2.1.0"
#mecab-python3 = "^1.0.10"
#unidic-lite = "^1.0.8"
#langid = "^1.1.6"
#pytorch-lightning = "^2.5.1.post0"
#wordsegment = "^1.3.1"
#pyjyutping = "^1.0.0"
#jamo = "^0.4.1"
#ko-pron = "^1.3"
#g2pk2 = "^0.0.3"
#unidecode = "^1.4.0"
#phonemizer = "3.2.1"
#eunjeon = {version = "^0.4.0", source = "artrajz", markers = "sys_platform == 'win32'"}
#python_mecab_ko = {version = "*", markers = "sys_platform != 'win32'"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
